site_name: Documentation Service Informatique - Piroux Industrie
theme: 
  name: material
nav:
  - Introduction: "index.md"
  - Cisco Discovery Protocol (CDP): cisco/cdp_commands.md
  - Commandes de base: cisco/basic_commands.md
  - DHCP: cisco/dhcp_commands.md
  - LLDP: cisco/lldp_commands.md
  - Ping: cisco/ping_commands.md
  - Sécurité: cisco/security_commands.md
  - Routeur:
    - Interfaces: cisco/routeur/interface_commands.md
    - Routage inter-vlan: cisco/routeur/intervlan_commands.md
  - Switch: 
    - Management: cisco/switch/switch_management.md
    - VLAN: cisco/switch/vlan_commands.md
    - VLAN Natif: cisco/switch/native_vlan_commands.md